// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://optktvmklhjeaahwjgll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wdGt0dm1rbGhqZWFhaHdqZ2xsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDEzMzAsImV4cCI6MjA3MzU3NzMzMH0.y_N0P4ebalw6Oe7qdX9pvUJw8VN8taYGijDz7GOpBpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});